"""empty message

Revision ID: 8221939e8cbc
Revises: 5e8b4c8457ec
Create Date: 2024-01-26 14:28:23.528043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8221939e8cbc'
down_revision = '5e8b4c8457ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###
